name: Lint

on:
  push:
    branches:
    - main

jobs:
  markdown-link-check:
    name: Markdown Lint Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
    
  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.x'
      - run: npm install -g markdownlint-cli@0.25.0
      - run: markdownlint '**/*.md'
