name: Link Checker

on:
  schedule:
    # Run weekly on Sunday at midnight UTC
    - cron: "0 0 * * 0"
  workflow_dispatch: # Allows manual run

permissions:
  contents: write
  pull-requests: write

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup pnpm
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2
        with:
          version: 12.6.0
          runtime: node@24
          run_install: true

      - name: Run link checker and fix dead links
        run: pnpm run check-links --write

      - name: Create Pull Request for Dead Links Clean-up
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: automatically remove dead links from sites.json"
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          signoff: false
          branch: chore/remove-dead-links
          delete-branch: true
          title: "chore: automatically remove dead links from sites.json"
          body: |
            This PR was automatically created by the weekly Link Checker workflow.
            It filters out dead links detected during the validation process.
          labels: |
            chore
            automated-pr
